[DEFAULT]
DataDir = ./data
PyEnsemblDataDir = ./data

BowtieArgs = --no-head -t -p 64 -N 0 -a -f --norc --score-min L,0,0
BowtieBuildIndexArg= --threads 32 -q
; CofoldParamFile= 
CofoldParamFile= -P ./cofold_rna_rna_params.par