[DEFAULT]

;Species (human, mouse)
Species = human
; Target gene ID
TargetGene = ENSG00000133703
; Length of candidate oligos
OligoLen = 16

; Genome Assembly
GenomeAssembly = 38
; Ensemble Release
EnsembleRelease = 113

; Layout of kmer containing left_flank,core_region,right_flank
MultiplicityLayout = 4,8,4

; Number of missmatches allowed in the core region for secondary target sites
MissmatchCoreRegion = 5

; maximum ddG allowed for repeated target sites
MaxddG = 5

; Number of Consecutive matches needed for RNas-h to cleave RNA
ConsecutiveMatchesCoreRegion = 5

; Directory for Bowtie2 data
Bowtie2Dir = ./data
; Directory to store result data
OligoDir = ./data
; Directory for PyEnsembl data
PyEnsemblDataDir = ./data

; Bowtie2 Arguments, refer to: https://bowtie-bio.sourceforge.net/bowtie2/manual.shtml
BowtieArgs = --no-head -t -p 64 -N 0 -a -f --norc --score-min L,0,0

BowtieBuildIndexArg= --threads 64 -q

; Rna cofold parameter file
CofoldParamFile=./cofold_rna_rna_params.par